spring.application.name=airBnb

#DB-Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnbProject
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

